### ISSUE TITLE
Trying to think of ideas to have IDE completions for `AccessorGenerator`

### ISSUE THREAD

**Issue by groovenectar** [quant-php/core#8]
Firstly, really liking the idea behind `AccessorGenerator`. Thank you. I found it via your article on Medium.

Have you thought about any ways to get autocompletion in an IDE?

I don't really like the only way I could think of so far because it repeats everything that's been defined -- kind of defeating one of the purposes of using the `AccessorTrait`:

```php
/**
 * @method getId
 * @method getFirstName
 * @method setFirstName
 * @method getLastName
 * @method setLastName
 */
class EntryModel {
	use AccessorTrait;

	#[Getter]
	private string $id;

	#[Getter] #[Setter]
	private string $firstName;

	#[Getter] #[Setter]
	private string $lastName;
}
```

I might personally just opt to not have completions rather than using DocBlock, but it would be super great to find a way. I've been digging online and haven't come up with the right solution yet.

Some frameworks use helper files that are generated in the project root:

https://github.com/barryvdh/laravel-ide-helper
https://github.com/dereuromark/cakephp-ide-helper

But perhaps there's a less bulky way of doing it...

**Comment by ThorstenSuckow** [comment]
hey @groovenectar, I haven't looked into IDE support yet but there is a [PHPStan extension](https://quant-php.dev/docs/packages/quant/phpstan) that supports the accessor automation. I'm not sure if that can be registered with an IDE?

**Comment by ThorstenSuckow** [comment]
hey @groovenectar, I have configured my PHPStorm Ide to use the project's `phpstan` configuration. 
Using the [phpstan-extension](https://github.com/quant-php/phpstan), all methods not explicitly declared are properly resolved to their annoted attributes, making the `@method` annotation obsolete! :)

Happy hacking!
